# Generated by Django 4.0 on 2022-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='count sold'),
        ),
    ]
