# Generated by Django 4.0 on 2022-06-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_count_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count_sold',
            field=models.IntegerField(default=0, null=True, verbose_name='count sold'),
        ),
    ]
