# Generated by Django 4.0 on 2022-06-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_count_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='products',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='count sold'),
        ),
    ]
