# Generated by Django 4.0 on 2022-06-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='profit',
        ),
    ]
